<center>
<p style="margin-top:50px;">
	<font color="#B0B0B0" size="1">
		Vulkan Hardware Database - © 2016 by <a href="http://www.saschawillems.de/" target="blank">Sascha Willems</a><br>
		<a href="https://www.khronos.org/vulkan/">Vulkan</a> and the Vulkan logo are trademarks of the <a href="http://www.khronos.org">Khronos Group Inc</a>.<br><br>
		The data presented is licensed under the <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.
	</font>
</p>
</center>
